Repository nareddyt/discover-rewards-notifier, pull requests merged in 2018-05, with the labels that each got.

#66 Improve offer matching algorithm
  src/background.js
Labels: bug-fix, enhancement

#68 Data update 5/4/18
  data/README.md
  data/cashback/data.json
  data/cashback/raw/1.html
  data/cashback/raw/2.html
  data/cashback/raw/3.html
  data/cashback/raw/4.html
  data/cashback/raw/5.html
  data/cashback/raw/6.html
  data/deal/data.json
  data/deal/raw.html
  docs/cashbacks.json
  docs/deals.json
Labels: data-update

#71 Bug Fix: Only match page titles if it has the whole word
  src/background.js
Labels: bug-fix

#73 Fix the image width to scale to look nice in mobile
  docs/index.md
Labels: bug-fix

#74 allow fixed offers to be loaded in tools/dataProcessor.js
  data/README.md
  data/cashback/data.json
  data/cashback/fixedInputData.json
  docs/cashbacks.json
  tools/dataProcessor.js
Labels: enhancement
